language: generic

sudo: required
services: 
  - docker

before_install:
  - docker build -t thomasmschauer/dcrc -f Dockerfile.dev .

script:
  - docker run -e CI=true thomasmschauer/dcrc npm run test